version: "3.8"
services:
  one:
    image: alpine
    command: ["/bin/sleep", "10000"]
    networks:
    - alpha
  two:
    image: alpine
    command: ["/bin/sleep", "10000"]
    networks:
    - alpha
    - beta
  three:
    image: alpine
    command: ["/bin/sleep", "10000"]
    networks:
    - beta

networks:
  alpha:
  beta:
