---
- hosts: all
  gather_facts: true
  become: true

  tasks:
    - name: Install the servers
      apt:
        name:
        - nginx
        - memcached
        state: present
        update_cache: yes
      tags:
      - packages
      - webservers

    - name: Configure the service
      template:
        src: templates/service/mysrv.conf.j2
        dest: /etc/mysrv.conf
      tags:
      - configuration