---
- hosts: all
  gather_facts: true
  become: true

  tasks:
    - name: Create mongod.conf file for MongoDB
      template:
        src: templates/mongodb/mongod.conf.j2
        dest: /etc/mongod.conf
      notify: mongo_restart
