---
- hosts: all
  become: yes
  vars:
    server_name: "{{ ansible_default_ipv4.address }}"
    document_root: /var/www/html
    app_root: html_demo_site-main
  vars_files:
    - secrets.yml
  tasks:
    - name: Update apt cache and install python-pip
      apt:
        name: python3-pip
        state: present
        update_cache: yes
      tags: python-pip
    - name: Install passlib python package
      pip:
        name: passlib
      tags: python-pip
    - name: Add a user to a password file and ensure permissions are set
      community.general.htpasswd:
        path: /etc/nginx/passwdfile
        name: "{{ NGINX_BASIC_AUTH_LOGIN }}"
        password: "{{ NGINX_BASIC_AUTH_PASSWORD }}"
        owner: root
        group: www-data
        mode: 0640
      tags: basic_user
    - name: Update apt cache and install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes
    - name: Copy website files to the server's document root
      copy:
        src: "{{ app_root }}"
        dest: "{{ document_root }}"
        mode: preserve
    - name: Apply Nginx template
      template:
        src: files/nginx.conf.j2
        dest: /etc/nginx/sites-available/default
      notify: Restart Nginx
    - name: Enable new site
      file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        state: link
      notify: Restart Nginx
    - name: Allow all access to tcp port 80
      ufw:
        rule: allow
        port: '80'
        proto: tcp
  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
