version: "3"
services:
  one:
    image: "alpine"
    command: ["/bin/sleep", "10000"]
    env_file:
      - envfile.txt
  two:
    image: alpine
    command: ["/bin/sleep", "10000"]
    environment:
      - MYVAR=VALUE
  three:
    image: alpine
    command: ["/bin/sleep", "10000"]
    environment:
      - TAG
